---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando Frontend de Fondes en DEV
      shell: |
        echo "Desplegando Frontend"
        /opt/fondes/dev/scripts/deployfrontend.sh
